version: '3'
services:
  mysql_db:
    image: mysql:8.0.28
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATAASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - ${DOCKET_NETWORK}
     
#Docker Networks
networks:
    ${DOCKET_NETWORK}:
      external: true
