version: '3'
services:
  mysql_db:
    image: mysql:8.0.28
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - project-net
     
#Docker Networks
networks:
    project-net:
      external: true
